### ISSUE TITLE
请问kcv改造版能用吗？

### ISSUE THREAD

**Issue by wyjtm** [smdhz/CodeA#1]
请问kcv改造版能用吗？   我把dll放到kcv里全都显示的是0  没有读取任务完成数

还是说要等下周任务更新吗？

**Comment by smdhz** [comment]
美佬版没试过，按理说问题不大……天知道那些鬼畜美佬都干了些什么

**Comment by wyjtm** [comment]
我放到kcv里进游戏没反应  读取不到数据  全都是0

**Comment by c933103** [comment]
yuyuvn版正常
