### ISSUE TITLE
4.1.1版本报错……求解决

### ISSUE THREAD

**Issue by mazhen8u8** [smdhz/CodeA#3]
1) 找不到方法:“System.IObservable`1<Fiddler.Session> Grabacr07.KanColleWrapper.KanColleProxy.get_api_req_sortie_battleresult()”。

结果: 尝试创建类型“CodeA.Base”的实例时发生异常。

结果: 无法激活部件“CodeA.Base”。
元素: CodeA.Base -->  CodeA.Base -->  AssemblyCatalog (Assembly="CodeA, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null")

结果: 无法从部件“CodeA.Base”获取导出“CodeA.Base (ContractName="Grabacr07.KanColleViewer.Composition.IPlugin")”。
元素: CodeA.Base (ContractName="Grabacr07.KanColleViewer.Composition.IPlugin") -->  CodeA.Base -->  AssemblyCatalog (Assembly="CodeA, Version=1.2.4.0, Culture=neutral, PublicKeyToken=null")

   在 System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   在 System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   在 System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   在 System.ComponentModel.Composition.Primitives.Export.get_Value()
   在 System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   在 System.ComponentModel.Composition.ExportServices.<>c__DisplayClass4`2.<CreateStronglyTypedLazyOfTM>b__1()
   在 System.Lazy`1.CreateValue()
   在 System.Lazy`1.LazyInitValue()
   在 System.Lazy`1.get_Value()
   在 Grabacr07.KanColleViewer.Composition.PluginService.<Load>d__21.MoveNext()

**Comment by smdhz** [comment]
请确认您的KCV 4.1来自http://pan.baidu.com/s/1ntEIPgH
CodeA.dll来自https://github.com/smdhz/CodeA/releases/tag/v2.0pre

**Comment by mazhen8u8** [comment]
使用以上连接中KCV，CODEA可以使用，然而其他插件（EVENTHP以及BATTELINFO）缺报错，换回KCV官网版本后，其他插件正常，CODEA报错。
不知链接中KCV与官网版本有何区别？

---

好吧原来是换了代理部分的修改版……原版不再支持了么？

**Comment by smdhz** [comment]
我也想支持原版，但是为了一个游戏废掉一个浏览器简直太蛋疼了
